[package]
name = "tersia"
version = "0.1.0"
authors = ["tauraamui <adamplewis@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.1.2"
bevy_obj = "0.1.0"
